"""
Regenerate _data/stats.yaml and _data/sites.yaml from a LAI4EO harmonised release.

Usage:
    python3 tools/build_site_data.py path/to/lai4eo_dataset_YYYY-MM-DD.csv

Run this after every database release so the homepage counters and map stay
in step with the data instead of drifting.
"""

import csv
import sys
import collections
from pathlib import Path

# how close two points must be (degrees) to be treated as the same site
CLUSTER_DEG = 0.4

# coordinates -> human-readable site name. Extend as new regions are added;
# anything unmatched falls back to "Unnamed site".
SITE_NAMES = [
    # (lat, lon, tolerance, name, country)
    (44.87, 11.96, 0.5, "Po Valley (Emilia-Romagna)", "Italy"),
    (45.26, 8.65, 0.5, "Lomellina rice district (Lombardy)", "Italy"),
    (-35.81, 142.99, 0.5, "Wimmera-Mallee (Victoria)", "Australia"),
    (48.33, 1.28, 0.5, "Beauce (Eure-et-Loir)", "France"),
    (42.82, 11.07, 0.5, "Maremma (Tuscany)", "Italy"),
    (39.79, 8.60, 0.5, "Oristano plain (Sardinia)", "Italy"),
    (45.25, 10.34, 0.5, "Cremona plain (Lombardy)", "Italy"),
    (45.21, 8.12, 0.5, "Vercelli rice district (Piedmont)", "Italy"),
]

# source_id -> contributing institution shown in map popups
CONTRIBUTORS = {
    "CNR-IREA_Francesco_2026-04-23": "CNR-IREA",
    "Monash_Yuval_2026-03-17": "Monash University",
    "Harvest_Josef_2026-03-17": "NASA Harvest / SatFarming",
}

# instrument model -> display label
INSTRUMENTS = {
    "LAI-2000": "LI-COR LAI-2000",
    "LAI-2200": "LI-COR LAI-2200",
    "LAI-2200c": "LI-COR LAI-2200C",
    "LP-80": "AccuPAR LP-80",
    "PocketLAI": "PocketLAI",
    "DHP": "Hemispherical photography",
}


def title_crop(name):
    """Crop names are inconsistently cased in the source data."""
    fixes = {"sorgum": "sorghum", "sugarbeet": "sugar beet"}
    name = name.strip().lower()
    return fixes.get(name, name)


def name_site(lat, lon):
    for slat, slon, tol, name, country in SITE_NAMES:
        if abs(slat - lat) < tol and abs(slon - lon) < tol:
            return name, country
    return "Unnamed site", ""


def yaml_str(s):
    return '"' + str(s).replace('\\', '\\\\').replace('"', '\\"') + '"'


def main(csv_path):
    rows = list(csv.DictReader(open(csv_path, newline="", encoding="utf-8")))

    def filled(key):
        return [r[key] for r in rows if r.get(key, "").strip()]

    # ---------- stats ----------
    crops = sorted({title_crop(c) for c in filled("dominant_species_or_crop")})
    instruments = sorted({INSTRUMENTS.get(i, i) for i in filled("lai_instrument_model")})
    years = sorted({d[:4] for d in filled("datetime_utc")})
    lai = [float(v) for v in filled("lai_mean")]
    areas = [float(v) for v in filled("esu_area")]
    contributors = sorted({CONTRIBUTORS.get(s, s) for s in filled("source_id")})

    clusters = cluster(rows)
    countries = sorted({c["country"] for c in clusters if c["country"]})

    stats = {
        "measurements": len(rows),
        "sampling_units": len(set(filled("esu_id"))),
        "field_plots": len(set(filled("plot_id"))),
        "crops": len(crops),
        "instruments": len(instruments),
        "countries": len(countries),
        "contributors": len(contributors),
        "sites": len(clusters),
        "year_min": years[0],
        "year_max": years[-1],
        "lai_min": min(lai),
        "lai_max": max(lai),
        "esu_area_min": min(areas),
        "esu_area_max": max(areas),
        "bbch_records": len(filled("phenology_stage")),
        "std_records": len(filled("lai_std")),
        "rtk_records": sum(1 for r in rows if r.get("gps_protocol", "").strip() == "RTK"),
    }

    out = ["# DO NOT EDIT - generated by tools/build_site_data.py",
           f"# source: {Path(csv_path).name}", ""]
    for k, v in stats.items():
        out.append(f"{k}: {v}")
    out.append("")
    out.append("crop_list:")
    out += [f"  - {c}" for c in crops]
    out.append("")
    out.append("instrument_list:")
    out += [f"  - {yaml_str(i)}" for i in instruments]
    out.append("")
    out.append("country_list:")
    out += [f"  - {c}" for c in countries]
    out.append("")
    out.append("contributor_list:")
    out += [f"  - {yaml_str(c)}" for c in contributors]
    out.append("")
    Path("_data/stats.yaml").write_text("\n".join(out), encoding="utf-8")

    # ---------- sites ----------
    lines = ["# DO NOT EDIT - generated by tools/build_site_data.py",
             f"# source: {Path(csv_path).name}", ""]
    for c in sorted(clusters, key=lambda c: -c["count"]):
        lines.append(f"- name: {yaml_str(c['name'])}")
        lines.append(f"  country: {yaml_str(c['country'])}")
        lines.append(f"  lat: {c['lat']:.4f}")
        lines.append(f"  lon: {c['lon']:.4f}")
        lines.append(f"  count: {c['count']}")
        lines.append(f"  year_min: {yaml_str(c['year_min'])}")
        lines.append(f"  year_max: {yaml_str(c['year_max'])}")
        lines.append(f"  contributor: {yaml_str(c['contributor'])}")
        lines.append(f"  main_crop: {yaml_str(c['main_crop'])}")
        lines.append("  crops:")
        for crop, n in c["crops"]:
            lines.append(f"    - {{ name: {yaml_str(crop)}, count: {n} }}")
        lines.append("  instruments:")
        for inst, n in c["instruments"]:
            lines.append(f"    - {{ name: {yaml_str(inst)}, count: {n} }}")
        lines.append("")
    Path("_data/sites.yaml").write_text("\n".join(lines), encoding="utf-8")

    write_points(rows, clusters)

    print(f"wrote _data/stats.yaml ({stats['measurements']} measurements)")
    print(f"wrote _data/sites.yaml ({len(clusters)} sites)")
    unnamed = [c for c in clusters if c["name"] == "Unnamed site"]
    for c in unnamed:
        print(f"  WARNING: no name for site at {c['lat']:.4f},{c['lon']:.4f} "
              f"- add it to SITE_NAMES in this script")


def cluster(rows):
    clusters = []
    for r in rows:
        if not r.get("lat", "").strip() or not r.get("lon", "").strip():
            continue
        lat, lon = float(r["lat"]), float(r["lon"])
        for c in clusters:
            if abs(c["lat"] - lat) < CLUSTER_DEG and abs(c["lon"] - lon) < CLUSTER_DEG:
                c["rows"].append(r)
                c["pts"].append((lat, lon))
                break
        else:
            clusters.append({"lat": lat, "lon": lon, "rows": [r], "pts": [(lat, lon)]})

    out = []
    for c in clusters:
        rs = c["rows"]
        lat = sum(p[0] for p in c["pts"]) / len(c["pts"])
        lon = sum(p[1] for p in c["pts"]) / len(c["pts"])
        name, country = name_site(lat, lon)
        crops = collections.Counter(
            title_crop(r["dominant_species_or_crop"])
            for r in rs if r["dominant_species_or_crop"].strip()
        )
        instruments = collections.Counter(
            INSTRUMENTS.get(r["lai_instrument_model"], r["lai_instrument_model"])
            for r in rs if r["lai_instrument_model"].strip()
        )
        years = sorted({r["datetime_utc"][:4] for r in rs if r["datetime_utc"].strip()})
        src = collections.Counter(r["source_id"] for r in rs).most_common(1)[0][0]
        out.append({
            "name": name,
            "country": country,
            "lat": lat,
            "lon": lon,
            "count": len(rs),
            "year_min": years[0] if years else "",
            "year_max": years[-1] if years else "",
            "contributor": CONTRIBUTORS.get(src, src),
            "main_crop": crops.most_common(1)[0][0] if crops else "",
            "crops": crops.most_common(),
            "instruments": instruments.most_common(),
        })
    return out




def write_points(rows, clusters):
    """
    Write assets/data/measurements.json - every measurement as a point, in a
    compact index-encoded form so the homepage map can cluster all of them
    without shipping a megabyte of JSON.

    Shape:
        {
          "crops":       ["alfalfa", ...],
          "instruments": ["AccuPAR LP-80", ...],
          "sites":       ["Po Valley (Emilia-Romagna)", ...],
          "points":      [[lat, lon, cropIdx, instIdx, year, lai, siteIdx], ...]
        }
    """
    import json

    crops, instruments, sites = [], [], []

    def index(seq, value):
        if value not in seq:
            seq.append(value)
        return seq.index(value)

    # map each row to the cluster it belongs to, for site labelling in popups
    def site_of(lat, lon):
        best, best_d = "", None
        for c in clusters:
            d = abs(c["lat"] - lat) + abs(c["lon"] - lon)
            if best_d is None or d < best_d:
                best, best_d = c["name"], d
        return best

    points = []
    for r in rows:
        if not r.get("lat", "").strip() or not r.get("lon", "").strip():
            continue
        lat, lon = round(float(r["lat"]), 5), round(float(r["lon"]), 5)
        crop = title_crop(r["dominant_species_or_crop"]) if r["dominant_species_or_crop"].strip() else ""
        inst = INSTRUMENTS.get(r["lai_instrument_model"], r["lai_instrument_model"])
        year = int(r["datetime_utc"][:4]) if r["datetime_utc"].strip() else 0
        lai = round(float(r["lai_mean"]), 2) if r["lai_mean"].strip() else None
        points.append([
            lat, lon,
            index(crops, crop),
            index(instruments, inst),
            year,
            lai,
            index(sites, site_of(lat, lon)),
        ])

    out = Path("assets/data/measurements.json")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        json.dumps(
            {"crops": crops, "instruments": instruments, "sites": sites, "points": points},
            separators=(",", ":"),
        ),
        encoding="utf-8",
    )
    print(f"wrote {out} ({len(points)} points, {out.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
