name: on-pull-request
run-name: On pull request activity

on:
  # run on any pull request activity
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  actions: read
  contents: write
  pull-requests: write

jobs:
  get-sources:
    if: github.event.action != 'closed'
    uses: ./.github/workflows/get-sources.yaml

  build-preview:
    # still run when PR closed to trigger deploy-preview
    if: ${{ !cancelled() && !failure() }}
    needs: get-sources
    uses: ./.github/workflows/build-preview.yaml
